import { Task } from "./task";

export const Tasks: Task[] = [
    { id: 1,
        name: "Prepare the assay",
        Category: "Education",
        Due_Date : "12/12/2022",
        Estimate : "8",
        Importance: "High",
     },
     { id: 2,
        name: "Format the PC",
        Category: "General cleanup",
        Due_Date : "12/10/2022",
        Estimate : "3",
        Importance: "Low",
     },
     { id: 3,
        name: "Contact the support team of XYZ software to ask about the guarantee pricing",
        Category: "General cleanup",
        Due_Date : "01/10/2022",
        Estimate : "0.5",
        Importance: "Medium",
     },
     { id: 4,
        name: "Translate the resume",
        Category: "Job Opportunity",
        Due_Date : "10/10/2022",
        Estimate : "2",
        Importance: "Low",
     },
     { id: 5,
        name: "Fix the power button of the TV",
        Category: "House improvements",
        Due_Date : "None",
        Estimate : "1",
        Importance: "Medium",
     },
     { id: 6,
        name: "Prepare the XD design",
        Category: "Prepare the XD design",
        Due_Date : "01/01/2022",
        Estimate : "8",
        Importance: "High",
     },
     { id: 7,
        name: "Email the faculty director about the progress",
        Category: "Final Year Project",
        Due_Date : "None",
        Estimate : "15",
        Importance: "",
     }
];